baseURL = 'https://marsomarwa.github.io/'
title = 'Marwa Marso'
languageCode = 'en-us'
theme = 'barks'
[params]

  favicon = "images/favicon.ico"
    [params.head]
        author = "Marwa Marso"
        description = "Hi, I'm Marwa, welcome to my website!"
        keywords = ["some", "keywords", "to", "describe", "this"]
    
    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:m.marso@nus.edu.sg"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/marwamarso/"
            weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar-square"
            url = "https://scholar.google.com/citations?user=eV1dyrMAAAAJ&hl=en"
            weight = 3
    
    [params.navigation]
    show_navigation = true
    [params.footer]
        show_footer = true

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#00CBC5"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1
    [[menu.main]]
        identifier = "research"
        name = "Research"
        url = "/research/"
        weight = 2
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
        weight = 3

    